"""
Unit tests for app.backend.services.transcript_service

Coverage:
  - parse_transcript() for .txt, .vtt, .srt, and plain pasted text
  - analyze_transcript() happy path, fallback on Ollama failure, and short input
"""
import json
import pytest
from unittest.mock import AsyncMock, MagicMock, patch

from app.backend.services.transcript_service import (
    parse_transcript,
    analyze_transcript,
    _parse_vtt,
    _parse_srt,
    _normalize,
    _fallback_result,
)


# ─── Fixtures ─────────────────────────────────────────────────────────────────

VTT_TRANSCRIPT = """\
WEBVTT

NOTE This file was generated by Zoom

1
00:00:01.000 --> 00:00:05.000
Interviewer: Tell me about your experience with Python.

2
00:00:06.000 --> 00:00:15.000
Jane Smith: I have worked with Python for six years, building REST APIs and data pipelines.

3
00:00:16.000 --> 00:00:24.000
I led a team that migrated a monolith to microservices using FastAPI and Docker.
"""

SRT_TRANSCRIPT = """\
1
00:00:01,000 --> 00:00:05,000
Interviewer: Can you describe your AWS experience?

2
00:00:06,000 --> 00:00:14,000
John Doe: I have three years of hands-on AWS experience, mainly EC2, S3, and Lambda.

3
00:00:15,000 --> 00:00:22,000
I also set up CI/CD pipelines using CodePipeline and GitHub Actions.
"""

PLAIN_TRANSCRIPT = """\
Interviewer: What is your experience with React?
Candidate: I built multiple production apps with React, Redux, and TypeScript.
I also have experience with Next.js and server-side rendering.
"""

OLLAMA_TRANSCRIPT_RESPONSE = {
    "fit_score": 82,
    "technical_depth": 75,
    "communication_quality": 80,
    "jd_alignment": [
        {"requirement": "Python", "demonstrated": True, "evidence": "six years of Python"},
        {"requirement": "Docker", "demonstrated": True, "evidence": "microservices using Docker"},
        {"requirement": "AWS",    "demonstrated": False, "evidence": None},
    ],
    "strengths": ["Strong Python background", "Microservices experience", "Leadership skills"],
    "areas_for_improvement": ["AWS depth could be stronger"],
    "bias_note": "Evaluation based solely on demonstrated skills and knowledge in the transcript.",
    "recommendation": "proceed",
}


# ─── parse_transcript ─────────────────────────────────────────────────────────

class TestParseTranscript:

    def test_vtt_strips_header_and_timestamps(self):
        result = parse_transcript(VTT_TRANSCRIPT, "interview.vtt")
        assert "WEBVTT" not in result
        assert "00:00:01" not in result
        assert "NOTE" not in result

    def test_vtt_retains_speech_content(self):
        result = parse_transcript(VTT_TRANSCRIPT, "interview.vtt")
        assert "six years" in result
        assert "FastAPI" in result
        assert "microservices" in result

    def test_vtt_strips_speaker_labels(self):
        result = parse_transcript(VTT_TRANSCRIPT, "interview.vtt")
        # Speaker prefix "Jane Smith:" should be stripped
        assert "Jane Smith:" not in result
        assert "Interviewer:" not in result

    def test_srt_strips_sequence_numbers(self):
        result = parse_transcript(SRT_TRANSCRIPT, "interview.srt")
        # Standalone digits used as sequence numbers should be gone
        lines = result.split()
        # No bare sequence-number token should survive
        assert "1" not in result.split() or "AWS" in result  # content present

    def test_srt_strips_timestamps(self):
        result = parse_transcript(SRT_TRANSCRIPT, "interview.srt")
        assert "00:00:01,000" not in result
        assert "-->" not in result

    def test_srt_retains_speech_content(self):
        result = parse_transcript(SRT_TRANSCRIPT, "interview.srt")
        assert "AWS" in result
        assert "Lambda" in result
        assert "GitHub Actions" in result

    def test_plain_txt_retains_content(self):
        result = parse_transcript(PLAIN_TRANSCRIPT, "interview.txt")
        assert "React" in result
        assert "TypeScript" in result
        assert "Next.js" in result

    def test_plain_txt_strips_speaker_labels(self):
        result = parse_transcript(PLAIN_TRANSCRIPT, "interview.txt")
        assert "Candidate:" not in result
        assert "Interviewer:" not in result

    def test_no_filename_treats_as_plain(self):
        result = parse_transcript(PLAIN_TRANSCRIPT)
        assert "React" in result

    def test_empty_vtt_returns_empty_string(self):
        result = parse_transcript("WEBVTT\n\n", "empty.vtt")
        assert result.strip() == ""

    def test_empty_srt_returns_empty_string(self):
        result = parse_transcript("", "empty.srt")
        assert result.strip() == ""

    def test_result_is_plain_string(self):
        result = parse_transcript(VTT_TRANSCRIPT, "interview.vtt")
        assert isinstance(result, str)

    def test_vtt_multiline_cue_merged(self):
        vtt = "WEBVTT\n\n1\n00:00:01.000 --> 00:00:04.000\nFirst line\nSecond line\n"
        result = _parse_vtt(vtt)
        assert "First line" in result
        assert "Second line" in result


# ─── analyze_transcript ───────────────────────────────────────────────────────

class TestAnalyzeTranscript:

    def _make_ollama_mock(self, body: dict):
        """Return a mock CLASS for httpx.AsyncClient.

        Python resolves __aenter__/__aexit__ through the TYPE, not the instance,
        so we must configure them on mock_class.return_value (what the class
        yields when instantiated) rather than on a bare AsyncMock instance.
        """
        mock_resp = MagicMock()
        mock_resp.json.return_value = {"response": json.dumps(body)}
        mock_resp.raise_for_status = MagicMock()

        mock_class = MagicMock()
        ctx = mock_class.return_value          # what httpx.AsyncClient(...) returns
        ctx.__aenter__ = AsyncMock(return_value=ctx)
        ctx.__aexit__ = AsyncMock(return_value=None)
        ctx.post = AsyncMock(return_value=mock_resp)
        return mock_class

    @pytest.mark.asyncio
    async def test_returns_dict_with_required_keys(self):
        mock_cls = self._make_ollama_mock(OLLAMA_TRANSCRIPT_RESPONSE)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                transcript="I have six years of Python and Docker experience.",
                jd_text="Looking for Python and Docker engineers.",
                candidate_name="Jane Smith",
            )

        required = {"fit_score", "technical_depth", "communication_quality",
                    "jd_alignment", "strengths", "areas_for_improvement",
                    "bias_note", "recommendation"}
        assert required.issubset(result.keys())

    @pytest.mark.asyncio
    async def test_fit_score_clamped_0_to_100(self):
        response = {**OLLAMA_TRANSCRIPT_RESPONSE, "fit_score": 150}
        mock_cls = self._make_ollama_mock(response)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have six years of Python experience building REST APIs and microservices at scale.",
                "Looking for a senior Python engineer with FastAPI and Docker experience.",
            )
        assert result["fit_score"] == 100

    @pytest.mark.asyncio
    async def test_negative_score_clamped_to_0(self):
        response = {**OLLAMA_TRANSCRIPT_RESPONSE, "technical_depth": -10}
        mock_cls = self._make_ollama_mock(response)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have six years of Python experience building REST APIs and microservices at scale.",
                "Looking for a senior Python engineer with FastAPI and Docker experience.",
            )
        assert result["technical_depth"] == 0

    @pytest.mark.asyncio
    async def test_recommendation_normalised_to_lowercase(self):
        response = {**OLLAMA_TRANSCRIPT_RESPONSE, "recommendation": "PROCEED"}
        mock_cls = self._make_ollama_mock(response)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have six years of Python experience building REST APIs and microservices at scale.",
                "Looking for a senior Python engineer.",
            )
        assert result["recommendation"] in ("proceed", "hold", "reject")

    @pytest.mark.asyncio
    async def test_invalid_recommendation_defaults_to_hold(self):
        response = {**OLLAMA_TRANSCRIPT_RESPONSE, "recommendation": "maybe"}
        mock_cls = self._make_ollama_mock(response)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have six years of Python experience building REST APIs and microservices at scale.",
                "Looking for a senior Python engineer.",
            )
        assert result["recommendation"] == "hold"

    @pytest.mark.asyncio
    async def test_jd_alignment_structure(self):
        mock_cls = self._make_ollama_mock(OLLAMA_TRANSCRIPT_RESPONSE)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I know Python and Docker very well and have used them in production for five years.",
                "We need a Python and Docker engineer with production experience.",
            )

        for item in result["jd_alignment"]:
            assert "requirement" in item
            assert "demonstrated" in item
            assert isinstance(item["demonstrated"], bool)

    @pytest.mark.asyncio
    async def test_short_transcript_returns_fallback(self):
        result = await analyze_transcript("Hi.", "Python developer needed.")
        assert result["fit_score"] == 50
        assert result["recommendation"] == "hold"

    @pytest.mark.asyncio
    async def test_empty_transcript_returns_fallback(self):
        result = await analyze_transcript("", "Python developer needed.")
        assert result["fit_score"] == 50

    @pytest.mark.asyncio
    async def test_ollama_network_error_returns_fallback(self):
        with patch("app.backend.services.transcript_service.httpx.AsyncClient") as mock_cls:
            mock_cls.return_value.__aenter__ = AsyncMock(side_effect=Exception("connection refused"))
            result = await analyze_transcript(
                "I have ten years of software engineering experience.",
                "We need an experienced engineer.",
            )
        assert result["fit_score"] == 50
        assert result["recommendation"] == "hold"

    @pytest.mark.asyncio
    async def test_ollama_invalid_json_returns_fallback(self):
        mock_resp = MagicMock()
        mock_resp.json.return_value = {"response": "not json at all!!!"}
        mock_resp.raise_for_status = MagicMock()

        mock_class = MagicMock()
        ctx = mock_class.return_value
        ctx.__aenter__ = AsyncMock(return_value=ctx)
        ctx.__aexit__ = AsyncMock(return_value=None)
        ctx.post = AsyncMock(return_value=mock_resp)

        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_class):
            result = await analyze_transcript(
                "I have experience with Python and cloud infrastructure.",
                "Looking for Python engineers.",
            )
        assert result["recommendation"] == "hold"

    @pytest.mark.asyncio
    async def test_bias_note_always_present(self):
        mock_cls = self._make_ollama_mock(OLLAMA_TRANSCRIPT_RESPONSE)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have strong Python and FastAPI skills acquired over five years in production environments.",
                "We are looking for a senior Python and FastAPI developer.",
            )
        assert result["bias_note"]
        assert len(result["bias_note"]) > 10

    @pytest.mark.asyncio
    async def test_strengths_list_max_6(self):
        response = {
            **OLLAMA_TRANSCRIPT_RESPONSE,
            "strengths": [f"strength {i}" for i in range(20)],
        }
        mock_cls = self._make_ollama_mock(response)
        with patch("app.backend.services.transcript_service.httpx.AsyncClient", mock_cls):
            result = await analyze_transcript(
                "I have worked with Python, Docker, AWS, React and TypeScript for the past seven years.",
                "We need a full-stack engineer with Python and cloud expertise.",
            )
        assert len(result["strengths"]) <= 6


# ─── _normalize ───────────────────────────────────────────────────────────────

class TestNormalize:

    def test_clamps_fit_score(self):
        result = _normalize({**OLLAMA_TRANSCRIPT_RESPONSE, "fit_score": 999})
        assert result["fit_score"] == 100

    def test_valid_proceed(self):
        result = _normalize({**OLLAMA_TRANSCRIPT_RESPONSE, "recommendation": "proceed"})
        assert result["recommendation"] == "proceed"

    def test_valid_reject(self):
        result = _normalize({**OLLAMA_TRANSCRIPT_RESPONSE, "recommendation": "reject"})
        assert result["recommendation"] == "reject"

    def test_unknown_recommendation_becomes_hold(self):
        result = _normalize({**OLLAMA_TRANSCRIPT_RESPONSE, "recommendation": "unknown"})
        assert result["recommendation"] == "hold"

    def test_empty_jd_alignment_preserved(self):
        result = _normalize({**OLLAMA_TRANSCRIPT_RESPONSE, "jd_alignment": []})
        assert result["jd_alignment"] == []


# ─── _fallback_result ─────────────────────────────────────────────────────────

class TestFallbackResult:

    def test_fallback_has_all_keys(self):
        fb = _fallback_result()
        required = {"fit_score", "technical_depth", "communication_quality",
                    "jd_alignment", "strengths", "areas_for_improvement",
                    "bias_note", "recommendation"}
        assert required.issubset(fb.keys())

    def test_fallback_fit_score_is_50(self):
        assert _fallback_result()["fit_score"] == 50

    def test_fallback_recommendation_is_hold(self):
        assert _fallback_result()["recommendation"] == "hold"
